### ISSUE TITLE
Project need to be Updated..!!

### ISSUE THREAD

**Issue by Smarpit-Singh** [TheAlphamerc/flutter_news_app#3]
With the BloC v5.0.0 BlocDelegate is deprecated and BlocSupervisor has been removed. Please, upgrade this project if possible..!!

**Comment by Smarpit-Singh** [comment]
*And null safety feature too

**Comment by TheAlphamerc** [comment]
@Smarpit-Singh Thanks foe taking interest in project. I'll migrate this project to latest BloC version on this weekend.
